services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - venv:/home/vscode/app/.venv
      - uv-cache:/home/vscode/.cache/uv
      - ../:/home/vscode/app:cached
      - ../config.ini:/home/vscode/.gamdl/config.ini
    environment:
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
    tty: true
    stdin_open: true

volumes:
  venv:
  uv-cache:
